import type { Metadata } from "next";
import { fontBody, fontData, fontHeading } from "@/assets/fonts";
import "@/css/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pl-PL"
      className={`${fontBody.variable} ${fontData.variable} ${fontHeading.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-primary-dark">{children}</body>
    </html>
  );
}
